version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mlflow-postgres
    environment:
      POSTGRES_DB: mlflow
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped
    networks:
      - mlflow-network

  mlflow:
    build: .
    container_name: mlflow-server
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - mlflow-data:/app/mlruns
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://mlflow:mlflow_password@postgres:5432/mlflow
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=./mlruns
    restart: unless-stopped
    networks:
      - mlflow-network

volumes:
  mlflow-data:
  postgres-data:

networks:
  mlflow-network:
    driver: bridge